<?php

define('JS_VERSION', '1.0');
define('ROOT', __DIR__); 
define('APP_DIR', ROOT . DIRECTORY_SEPARATOR . 'app' . DIRECTORY_SEPARATOR);
define('PAGE_DIR', APP_DIR . 'pages' . DIRECTORY_SEPARATOR);
define('APPLIB_DIR', APP_DIR . 'lib' . DIRECTORY_SEPARATOR);
define('MIGRATIONS_DIR', ROOT . DIRECTORY_SEPARATOR . 'migrations' . DIRECTORY_SEPARATOR);

define('SYS_DIR', ROOT . DIRECTORY_SEPARATOR . 'system' . DIRECTORY_SEPARATOR);
define('LIB_DIR', SYS_DIR . 'lib' . DIRECTORY_SEPARATOR);
define('LOG_DIR', ROOT . DIRECTORY_SEPARATOR . 'logs' . DIRECTORY_SEPARATOR);